language: node_js
node_js: 8
git:
  depth: false
branches:
  only:
    - experimental/screenshot-testing

matrix:
  include:
    - os: osx
      env: TEST_SUITE=screenshots
    - os: linux
      env: TEST_SUITE=units

install:
  - npm i
script:
  - npm run test:ci
after_failure:
  - npm run upload:screenshots
