language: node_js
node_js: 8
dist: trusty
sudo: required
git:
  depth: false
branches:
  only:
    - experimental/screenshot-testing

env:
  - TEST_SUITE=units
  - TEST_SUITE=screenshots

install:
  - npm i
script:
  - npm run test:ci
after_failure:
  - npm run upload:screenshots
