language: node_js
node_js: 8
git:
  depth: false
branches:
  only:
    - experimental/screenshot-testing

# os: linux
dist: trusty
sudo: required

env:
  - TEST_SUITE=screenshots
  - TEST_SUITE=units

# matrix:
#   include:
#     - os: osx
#       osx_image: xcode9.3beta # Uses OSX 10.13
#       env: TEST_SUITE=screenshots
#     - os: linux
#       dist: trusty
#       sudo: required
#       env: TEST_SUITE=units

install:
  - npm i
script:
  - npm run test:ci
after_failure:
  - npm run upload:screenshots
