language: node_js
node_js: 8
git:
  depth: false
branches:
  only:
    - master

dist: trusty
sudo: required

env:
  - TEST_SUITE=screenshots
  - TEST_SUITE=units

install:
  - npm i
script:
  - npm run test:ci
after_script:
  - npm run upload:screenshots
