language: node_js
git:
  depth: false
# branches:
#   only:
#     - master
#     - experimental/screenshot-testing

dist: trusty
sudo: required

matrix:
  include:
    - node_js: 8
      env: TEST_SUITE=unit
      install: npm i
      script: npm run test:unit-ci

    - node_js: 8
      env: TEST_SUITE=screenshots
      install: npm i
      script: npm run test:image-diff-ci
      after_script:
        - echo $SERVICE_ACCOUNT_KEY > ./key.json
        - npm run upload:screenshots
        - rm ./key.json
