language: node_js
node_js: 8
dist: trusty
sudo: required
git:
  depth: false
branches:
  only:
    - experimental/screenshot-testing
addons:
  chrome: stable

env:
  - TEST_SUITE=units
  - TEST_SUITE=screenshots

install:
  - npm i
script:
  - ./scripts/run-travis-tests.sh
